### ISSUE TITLE
Butuh bantuan master

### ISSUE THREAD

**Issue by AzarinMC** [AkiRaID/akirabotv1#2]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'tiktok-scraper'
Require stack:
- /data/data/com.termux/files/home/akirabotv1/akirabot.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/akirabotv1/akirabot.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/data/data/com.termux/files/home/akirabotv1/akirabot.js' ]
}

**Comment by AkiRaID** [comment]
Ketik cd setelah gitclone
Lalu cd akirabotv1
bash install.sh
node index.js

**Comment by AzarinMC** [comment]
> Ketik cd setelah gitclone
> Lalu cd akirabotv1
> bash install.sh
> node index.js

Sudah bang tetep gk bisa 😭😭

**Comment by AzarinMC** [comment]
> Ketik cd setelah gitclone
> Lalu cd akirabotv1
> bash install.sh
> node index.js

Bisa sih kok tapi gk respon botnya

**Comment by AkiRaID** [comment]
Sabar masih proses
